# Generated by Django 5.1 on 2024-10-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_intelproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intelproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='intelproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='intelproduct',
            name='stock',
        ),
        migrations.AlterField(
            model_name='intelproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AlterField(
            model_name='intelproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
