# Generated by Django 5.1 on 2024-10-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_intelproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelproduct',
            name='image',
            field=models.ImageField(default='default_image_path.jpg', upload_to='product_images/'),
        ),
    ]
