# Generated by Django 5.1 on 2024-11-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_amdproduct_id_alter_intelproduct_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='amd_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.amdproduct'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='intel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.intelproduct'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.product'),
        ),
    ]
