# Generated by Django 5.1.3 on 2025-02-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='No Address Provided'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
    ]
