# Generated by Django 5.1.3 on 2025-02-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_order_address_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='Not Provided', max_length=255),
        ),
    ]
