# Generated by Django 5.1.3 on 2025-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='amd_products',
            field=models.ManyToManyField(blank=True, to='store.amdproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='intel_products',
            field=models.ManyToManyField(blank=True, to='store.intelproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
