# Generated by Django 5.1.3 on 2025-03-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_order_amd_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
