# Generated by Django 5.1.3 on 2025-03-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_invoice_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amdproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='intelproduct',
            name='description',
        ),
    ]
