# Generated by Django 5.1.3 on 2025-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
